# Generated by Django 5.2.5 on 2025-10-08 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='metadata',
            field=models.JSONField(default=dict, help_text='Additional shop specific data'),
        ),
    ]
