# Generated by Django 5.2.5 on 2025-10-09 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssm', '0002_alter_shop_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotmetadata',
            name='assigned_sim_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lotmetadata',
            name='unassigned_sim_count',
            field=models.IntegerField(default=0),
        ),
    ]
