# Generated by Django 5.2.5 on 2025-10-03 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssm', '0002_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssmauthuser',
            name='needs_password_reset',
            field=models.BooleanField(default=False),
        ),
    ]
