# Generated by Django 5.2.5 on 2025-09-23 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssm', '0002_user_auth_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_trial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
