# Generated by Django 5.2.5 on 2025-10-07 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssm', '0004_shop_owner_productcategory_product_productsale_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_barcode_d008ac_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='barcode',
        ),
    ]
