# Generated by Django 5.2.5 on 2025-09-26 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssm', '0005_shop_shopauditlog_shopinventory_shopperformance_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='teammetadata',
            table='team_metadata',
        ),
    ]
