# Generated by Django 5.2.5 on 2025-10-09 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssm', '0005_alter_user_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simcardtransfer',
            old_name='sim_cards',
            new_name='lots',
        ),
    ]
