# Generated by Django 5.2.5 on 2025-10-07 23:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssm', '0005_remove_product_products_barcode_d008ac_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('barcode', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('damaged', 'Damaged'), ('returned', 'Returned')], default='available', max_length=20)),
                ('sold_date', models.DateTimeField(blank=True, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('allocated_date', models.DateTimeField(auto_now_add=True)),
                ('allocated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocated_instances', to='ssm.user')),
                ('current_shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_instances', to='ssm.shop')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='ssm.product')),
                ('sold_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_instances', to='ssm.user')),
            ],
            options={
                'db_table': 'product_instances',
                'indexes': [models.Index(fields=['serial_number'], name='product_ins_serial__bdf510_idx'), models.Index(fields=['barcode'], name='product_ins_barcode_5074b3_idx'), models.Index(fields=['product', 'status'], name='product_ins_product_72c412_idx'), models.Index(fields=['current_shop', 'status'], name='product_ins_current_ecd091_idx')],
            },
        ),
    ]
