# Generated by Django 5.2.5 on 2025-09-30 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssm', '0007_teamgroup_teamgroupmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamgroup',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_team_groups', to='ssm.user'),
        ),
    ]
