# Generated by Django 5.2.5 on 2025-10-01 10:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssm', '0008_teamgroup_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminOnboarding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_verified', models.BooleanField(default=False)),
                ('profile_completed', models.BooleanField(default=False)),
                ('business_info_completed', models.BooleanField(default=False)),
                ('system_tour_completed', models.BooleanField(default=False)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('billing_active', models.BooleanField(default=False)),
                ('billing_start_date', models.DateTimeField(blank=True, null=True)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('profile_completed_at', models.DateTimeField(blank=True, null=True)),
                ('business_info_completed_at', models.DateTimeField(blank=True, null=True)),
                ('system_tour_completed_at', models.DateTimeField(blank=True, null=True)),
                ('onboarding_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_status', to='ssm.user')),
            ],
            options={
                'db_table': 'admin_onboarding',
            },
        ),
        migrations.CreateModel(
            name='BusinessInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.TextField()),
                ('business_type', models.TextField(blank=True, null=True)),
                ('registration_number', models.TextField(blank=True, null=True)),
                ('kra_pin', models.TextField(blank=True, null=True)),
                ('physical_address', models.TextField(blank=True, null=True)),
                ('county', models.TextField(blank=True, null=True)),
                ('town', models.TextField(blank=True, null=True)),
                ('contact_person', models.TextField(blank=True, null=True)),
                ('contact_phone', models.TextField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_info', to='ssm.user')),
            ],
            options={
                'db_table': 'business_info',
            },
        ),
    ]
