# Generated by Django 5.2.5 on 2025-10-01 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssm', '0009_adminonboarding_businessinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessinfo',
            old_name='business_name',
            new_name='dealer_code',
        ),
        migrations.RemoveField(
            model_name='businessinfo',
            name='business_type',
        ),
        migrations.RemoveField(
            model_name='businessinfo',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='businessinfo',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='businessinfo',
            name='county',
        ),
        migrations.RemoveField(
            model_name='businessinfo',
            name='kra_pin',
        ),
        migrations.RemoveField(
            model_name='businessinfo',
            name='physical_address',
        ),
        migrations.RemoveField(
            model_name='businessinfo',
            name='registration_number',
        ),
        migrations.RemoveField(
            model_name='businessinfo',
            name='town',
        ),
    ]
