# Generated by Django 5.2.5 on 2025-10-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssm', '0010_rename_business_name_businessinfo_dealer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinfo',
            name='dealer_code',
            field=models.TextField(unique=True),
        ),
    ]
