# Generated by Django 5.2.5 on 2025-10-02 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssm', '0011_alter_businessinfo_dealer_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
